AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Scheduled Discogs collection sync to a static S3-hosted website.

Parameters:
  TargetBucketName:
    Type: String
    Description: S3 bucket where recordList.html should be written.
  TargetObjectKey:
    Type: String
    Default: recordList.html
    Description: Object key to update on each sync.
  DiscogsUsername:
    Type: String
    Description: Discogs username to sync from.
  DiscogsFolderId:
    Type: Number
    Default: 0
    Description: Discogs folder id (0 is All).
  DiscogsTokenSecretArn:
    Type: String
    Description: ARN of Secrets Manager secret containing the Discogs token.
  ScheduleExpression:
    Type: String
    Default: rate(6 hours)
    Description: EventBridge schedule expression for sync cadence.
  DiscogsUserAgent:
    Type: String
    Default: herbadis-website-discogs-sync/1.0
  DiscogsPerPage:
    Type: Number
    Default: 100
  DiscogsSleepSeconds:
    Type: String
    Default: "1.1"
  TargetCacheControl:
    Type: String
    Default: max-age=300

Resources:
  DiscogsSyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Pull Discogs collection and upload static record list HTML to S3.
      Runtime: python3.12
      CodeUri: lambda/
      Handler: app.lambda_handler
      MemorySize: 512
      Timeout: 180
      Environment:
        Variables:
          TARGET_BUCKET_NAME: !Ref TargetBucketName
          TARGET_OBJECT_KEY: !Ref TargetObjectKey
          TARGET_CACHE_CONTROL: !Ref TargetCacheControl
          DISCOGS_USERNAME: !Ref DiscogsUsername
          DISCOGS_FOLDER_ID: !Ref DiscogsFolderId
          DISCOGS_TOKEN_SECRET_ID: !Ref DiscogsTokenSecretArn
          DISCOGS_USER_AGENT: !Ref DiscogsUserAgent
          DISCOGS_PER_PAGE: !Ref DiscogsPerPage
          DISCOGS_SLEEP_SECONDS: !Ref DiscogsSleepSeconds
      Policies:
        - Statement:
            - Sid: WriteTargetObject
              Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub arn:${AWS::Partition}:s3:::${TargetBucketName}/${TargetObjectKey}
            - Sid: ReadDiscogsTokenSecret
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref DiscogsTokenSecretArn
      Events:
        ScheduledSync:
          Type: Schedule
          Properties:
            Name: !Sub ${AWS::StackName}-discogs-sync
            Description: Refresh recordList.html from Discogs collection.
            Schedule: !Ref ScheduleExpression
            Enabled: true

Outputs:
  DiscogsSyncFunctionName:
    Description: Lambda function name for manual invoke/testing.
    Value: !Ref DiscogsSyncFunction
  DiscogsSyncFunctionArn:
    Description: Lambda function ARN.
    Value: !GetAtt DiscogsSyncFunction.Arn
